version: '3'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/grocery-store
      - JWT_SECRET=grocery_store_secret_key_change_in_production
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - grocery-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - grocery-network
    restart: unless-stopped

networks:
  grocery-network:
    driver: bridge

volumes:
  mongo-data: 